### PR TITLE
Schmeatic and PCB Update of Addon Board (ESP32miniBT)

### PR DESCRIPTION
**Pull request by junaidwien**
Updates made to schematic:
- I2S MEMS microphone (CMM-4030D-261-I2S-TR) has been added including a 100k pulldown resistor and a 100nF decoupling capacitor
- all small SMD components have been updated to 0805 footprint
- Jumper JP1 and JP2 are removed to save space
- J2 (and J3) has been completely removed
- R1 and R2 have been replaced by 100k resistors to reduce costs for BOM
- C6 and C7 are replaced by 0.1 uf resistors to reduce costs for BOM

Update made to the PCB:
- all SMD components are put on the back side (same side as ESP32)
- all components are relocated to create enough space
- I2S MEMS microphonei s added (incl 100k resistor and 100nF capacitor)
- Pogramming pads are placed on the front side (replacing J2 Pin header)
- no size increase of PCB area

### CODE REVIEW

**Comment by benjaminaigner** [comment]
Dear @junaidwien 

THX for the PR. There are a few additonal request, before we can merge this:

* Please include an I2S MEMS microphone (@ChrisVeigl  please tell us the pins needed)
* We used a SPH0645 microphone, but when all SMD parts should be mounted on the same side, we need a microphone with an upfacing port, e.g.: CMM-4030D-261-I2S-TR


* Change the PCB accordingly:

**PCB changes:**

* if possible without major PCB area increase: place all 0805 parts on the same side as the esp32
* place the programming pads on front (same side as the connector)
* the MEMS microphone must be placed as far away from the antenna as possible

**Comment by ChrisVeigl** [comment]
as far as the pin connection of the i2s-microphone is concerned, desired GPIO pins can be used for the i2s signal,
however, following pins are recommend:

MIC_WS (LRCL) is connected to ESP32_WROOM IO15 
MIC_SD (DOUT) is connected to ESP32_WROOM IO32 , with a 100k pulldown
MIC_SCK (BCKL) is connected to ESP32_WROOM IO14
the L/R selection can be grounded.
a 100nF cap is recommended for decoupling at the supply pins.

see:

mic_connection

**Comment by junaidwien** [comment]
The PCB is now updated and the necessary changes have bee addded.

**Comment by benjaminaigner** [comment]
Dear @junaidwien 

there are a few minor changes before we can merge:

SCH:
* Please fix the "unconnected" errors in ERC by placing a "no connect" symbol on pin13 & pin23 of the ESP32
* Please include the library symbol of the MEMS microphone

PCB:
* Please place dimensions of the PCB (F_FAB layer)
* Increase the trace width of the 3v3 trace between C1 & C3

BOM:

Please update the order numbers for the used parts in BOM.txt and update the interactive BOM (see: https://github.com/openscopeproject/InteractiveHtmlBom/ )

After these changes, I think we can merge & order the PCBs

@ChrisVeigl  If possible, please have a look

**Comment by ChrisVeigl** [comment]
I think it looks good !
(did not have time to check the footprints, though ...)
should we connect the enable pin of the mic to a GPIO of the ESP32 (its "always on" ...)

**Comment by junaidwien** [comment]
@benjaminaigner 
SCH:
The unconnected errors ocurred due to the missing symbol library of the microphone.
The lib subfolder has now been updated with the symbol, library and 3D model and linked, there should be no unconnected errors anymore for those pins.

PCB:
The PCB has been updated accordingly (dimensions + trace width correction)

BOM:
The BOM.txt and the interactive BOM are also updated. I hope the selected components are okay - maybe someone should look through them.

@ChrisVeigl 
I connected the enable pin to IO13, due to its proximity for now. I hope the pin was not engaged before. If so let me know, and i will change it accordingly.

**Comment by benjaminaigner** [comment]
Dear @junaidwien 

THX, very nice!

Last few changes:

Please review the silkscreen (I usually upload the board to aisler.net):

* "BT module v0.4" is too close to the edge
* "IO12 connected to GND": there is a via in the text
* "C5" also a via in the text

Then we will produce the first batch!

**Comment by benjaminaigner** [comment]
Works for me!!!

**Comment by junaidwien** [comment]
@benjaminaigner 
The changes to the silkscreen have been made.
But when uploading to aisler.net I saw that the text on the "open hardware" logo is not very clean, due to the thickness of the font. I wanted to replace it with a bigger logo, but the footprint for that is too big again. Maybe it looks better on the actual print.
Thank you for the feedback!

**Pull request merged**
