### PR TITLE
Improving ESP32 addon interoperability

### PR DESCRIPTION
**Pull request by benjaminaigner**
This branch contains many improvements regarding the ESP32 addon:

* AT UG: upgrading the esp32 (THX to @junaidwien )
* AT BC for arbitrary interaction from GUI to ESP32 addon

This branch can't be merged fast-forward, because we did some of its changes in the master branch already,
so we have to manually pick the changes.

### CODE REVIEW

**Comment by klues** [comment]
If you want, I could try to resolve the conflicts.

**Comment by benjaminaigner** [comment]
The conflicts arise from the FLipWare code and won't be hard to resolve.

Nevertheless, we should discuss following aspects:
This branch also contains:
* changes in the C# GUI: according to @ChrisVeigl , these changes don't work well, and we should consider not using them at all, if we go further with the WebGUI
* changes in the default slot settings (especially a higher deadzone setting)

**Comment by klues** [comment]
I've merged master into this branch and resolved the merge conflicts, hopefully correctly, see https://github.com/asterics/FLipMouse/pull/43/commits/c3e0a0cbb6413921ed6eb1a28e41b387439fa103.

**Comment by benjaminaigner** [comment]
@klues 
THX for rebasing.

@ChrisVeigl   @klues 
What do you think about the C# GUI?

**Comment by klues** [comment]
I don't know, what are the changes that don't work well?

**Comment by ChrisVeigl** [comment]
the problems in the GUI are related to the pairing function (devices only shown as MAC adresses, no possibility to remove a paired device).  As we can not solve these problems now, i suggest to merge and improve this point later ....

**Comment by ChrisVeigl** [comment]
coming back to the question if we should discard the GUI changes in this branch.... -> i am unsure ;)

this GUI version accepts strings with prefix " "PAIRING:" from the firmware - and adds received BT-MAC addresses to a combo box.

Using an "Unpair" button, the selected MAC address can be unpaired using 
sendBluetoothCommand("$DP" + i)    

If this functionality is not useful for our intended pairing/unpairing procedure, we can discard it.
otherwise we should merge / try to resolve the merge conflics...

**Comment by ChrisVeigl** [comment]
in the meantime BT-Firmware updates from the GUI work for the FABI device, see
https://github.com/asterics/FABI/commit/f8fdcd3d979b030fdc799a500ed6f63606eed654

i think it would be good to get this done in the FlipMouse soon as well. 
Maybe we should pull the firmware support for AT UG into the master and adapt der GUI there, leaving the BT pairing features in this branch for later revision / uptake.

**Comment by benjaminaigner** [comment]
All changes are already merged or implemented otherwise, closing.

**Pull request closed without merging**
