### PR TITLE
Eeprom performance

### PR DESCRIPTION
**Pull request by klues**
I've opened a pull request for this branch for discussing further changes.
As discussed and additionally:
1. Please return "OK" for commands `AT SA`, `AT LO`, `AT DE`
2. Please update the version string for `AT ID`. Should the WebGUI provide a fallback for saving configuration on older versions of the Firmware? I don't think it makes much sense, since then also auto-save will not work well and we would need a completely different workflow, like in the C# GUI. So maybe I'll just refuse to connect to older firmwares in the WebGUI?!

### CODE REVIEW

**Comment by ChrisVeigl** [comment]
* AT SA, AT DE and AT LO   now return the acknowledge message "OK" upon completion
* version number was increased to v2.11
* the EEPROM layout and IR storage were completely changed, using EEPROM block read/write now
* the average slot store time thus decreased from ~1500 ms to  ~50ms   ( -> factor 30 :-)
* the C# GUI does currently not use the acknowlege handshake for saving slots because full speed seems possible (.exe is updadted for testing)

Please check (and if possible test also the IR functions) so that we can find bugs and eventually merge ...

**Comment by ChrisVeigl** [comment]
* the AT DE command for deleting all slots now accepts a parameter for removing single slots: 
* AT DE <slotname> removes this slot (if the name exists)
* AT DE without parameters still deletes all slots

**Comment by klues** [comment]
One thing I just noticed: `AT IL` should return something even if there are no IR commands stored, e.g. `OK` or just a line break `\n`.

Thanks for the other improvements, I'll test them tomorrow.

**Review by benjaminaigner — COMMENTED** [review]
Nice approach!

**Comment by klues** [comment]
Just added a command `AT RS` for resetting to default config. It generally works, but is a little bit hacky with a reboot by software. I don't know if I can use this for my testing suite since reboot looses and reconnects the COM-port. Do you know something better how we could do it without reboot?!

**Comment by benjaminaigner** [comment]
Just 28Bytes of Flash :-).
Another approach would be:
* Move the FlipMouse.ino:64 (struct slotGeneralSettings settings) values into
defines or another `const` struct (Flash memory usage won't change as they are stored either way)
* Load these const values into `settings` and call `initButtons()`

**Comment by benjaminaigner** [comment]
68B more flash, but 8B less RAM usage :-).
`AT RS` now:
* deletes all slots
* copies the defaultSettings constant over the settings struct
* inits the buttons with the default settings
* saves this slot (name is set in the defaultSettings struct)
* loads this slot

**Comment by klues** [comment]
looks great, thanks! 👍 
I was just about to search for the relevant code parts when you've already implemented it ;)
Just tested it, works perfectly!

**Comment by ChrisVeigl** [comment]
I just added handling of the "AT NE" problem in case no slots are actually stored.
Thereby I realized that we do not have any error responses from the Flipmouse in case a command cannot be performed properly. (Sometime "OK" was returned, somtimes nothing ...)

Now, "E: not found" is returned instead of "OK" if a slot (or requested slot/ir-name) does not exist. (still, "AT LO" progresses to slot 0 in case a slot name is not valid - i did not schange that because i was not sure if we need it elsewhere.) We could also use "E: not found" instead of the "?" which indicates unknow commands, or use a more distinct error message.

Probably we can find other occasions where we should return an error message.
This should also be added to FABI for compatibility....

**Comment by klues** [comment]
Wrote some automated tests: https://asterics.github.io/Addon-Bluetooth-WebGUI/webgui/test_fm.htm which work fine.
So let's merge!

**Pull request merged**
