### PR TITLE
Added button state output to AT SR reporting of live values

### PR DESCRIPTION
**Pull request by benjaminaigner**
If reporting of live values is started (`AT SR`),
an additional field is transmitted, which represents all button states (physical or virtual), e.g.:
```
VALUES:520,430,642,786,210,0,0,00000000000
VALUES:520,430,642,786,210,0,0,10000000000
VALUES:520,430,642,786,210,0,0,01000000000
VALUES:520,430,642,786,210,0,0,00000000000
```
Position is determined by the `*_BUTTON` defines from __buttons.h__

### CODE REVIEW

**Comment by ChrisVeigl** [comment]
OK - nice - i could add that to the FABI firmware, too!

**Comment by benjaminaigner** [comment]
@ChrisVeigl 
Already done:
https://github.com/asterics/FABI/pull/15
but for this PR, we need updates in boths GUIs, I don't think it is compatible.

**Comment by ChrisVeigl** [comment]
For the FABI C#-GUI there was no problem,
the FlipMouse C#-GUI needed a small adaptation because it checks if the number of expected arguments is correct.
(please try the new version - it displays button states of B1, B2 and B3 in the buttons tab!)

However i suspect that the transmitted buttonstate is not always correct. Maybe a problem with the ButtonDebouncer's internal state or with the release_all() function ...  (Pls. especially test slot changes via strong puff etc.)

**Comment by klues** [comment]
I've added an additional value, the current slot: `VALUES:520,430,642,786,210,0,0,00000000000,<slot-id>` in order to be able to show the current slot in the WebGUI-Visualization. @ChrisVeigl please check if this causes Problems in the C# GUI.

**Comment by ChrisVeigl** [comment]
yes - it will break compatibility to the C#-GUI - but it is an easy fix...
however: it would be interesting if you wnat to change the report format further  ;-)

I suppose this is also planned for the FlipMouse and will be added to FlipWare soon ?

**Comment by klues** [comment]
This is FlipWare, I think your question was aimed at FABI?! Yes, would make sense to also add it to FABI.
I currently don't know more values that I need, but maybe it's possible to change it in C# in a way that further values wouldn't break everything?

**Comment by ChrisVeigl** [comment]
yes - i meant FabiWare  ;-)
i could remove the check for the correct  number of paramters completely - but it was meant to be a safety measure to prevent wrong formats / missing values  ...

**Comment by benjaminaigner** [comment]
Maybe test for a minimum number of parameters?
More parameters won't hurt (upwards compatibility), but missing parameters won't lead to errors.

**Comment by ChrisVeigl** [comment]
Ok done!
also available in FabiWare and FabiGUI now,
auto-slot change in both GUIs supported!

**Comment by klues** [comment]
perfect, thanks 👍

**Comment by benjaminaigner** [comment]
Nice, THX!

**Pull request merged**
